#ifndef __psrfits_drifttool_cmd__
#define __psrfits_drifttool_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -o: Basename for the output files */
  char outputbasenameP;
  char* outputbasename;
  int outputbasenameC;
  /***** -nsubint: Number of subints per output file */
  char nsubintP;
  int nsubint;
  int nsubintC;
  /***** -advance: Number of subints to advance for next file */
  char advP;
  int adv;
  int advC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

